name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="docker_image=${{ secrets.DOCKERHUB_USERNAME }}/sura-proyect" \
            -var="docker_tag=latest" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="key_name=${{ secrets.AWS_KEY_NAME }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Get EC2 Info
        working-directory: ./terraform
        run: |
          PUBLIC_IP=$(terraform output -raw instance_public_ip)
          echo "🚀 API desplegada exitosamente en EC2"
          echo "🌐 URL: http://$PUBLIC_IP:8080"
